### PR TITLE
Add multiple fixed columns, fix style bugs, remove throttle (#1)

### PR DESCRIPTION
**Pull request by MetalWeirdo**
* Update class names

* Add dev example

* Add deps

* Add multi fixed columns

* Add fullwidth x-scroll, fix example styles

* Fix width\height scrollbar padding

* Fix sticky columns widths, fix scrollbar using wrong table scroll position

* Fix cell height calculation

* Move to border-box height width sizing, add only real table width sizing

* Fix log

* Add end scroll event callback

* Fix deps, fix throttle, add on scroll

* Add handle scroll event on scroll content resize

* Fix visible scroll in firefox and ie

* Fix not full content scroll bar visible

* Add onScrollEnd event

* Fix performance for ie

* Remove throttles from scroll event for ie

* Sync two scrolls events

* Fix scroll init

* Fix readme

* Fix lint errors, fix package.json

### CODE REVIEW

**Comment by MetalWeirdo** [comment]
This fork has a lot of fixes by @ditkachuk !

**Comment by maxhudson** [comment]
@MetalWeirdo this looks good. I'm not going to merge until I can try it myself and unfortunately I'm just now leaving for a month long vacation without a computer, but when I'm back I'll check it out. Thanks for taking the time to look at it yourself!

**Comment by MetalWeirdo** [comment]
I just need to change the package name I think ;) Have a nice holiday!

**Comment by hurrtz** [comment]
How is the status here?

**Comment by maxhudson** [comment]
@hurrtz I'll try to merge this tonight, once I review.

**Comment by hurrtz** [comment]
Cool! Thing is that your current build will fail with react 16 because you still use react.PropTypes which they kicked out. I am currently running with the fork and it looks good :) Looking forward to seeing this table get updated :)

**Comment by maxhudson** [comment]
@hurrtz https://github.com/henrybuilt/react-sticky-table/pull/11

**Pull request closed without merging**
