### PR TITLE
feat(upgrade): upgrade all package and use jsdom-global and adapter o…

### LINKED ISSUE #38: Type Error: Super expression must either be null or function
Hey, not sure why this is happening, but I keep receiving the following error:

screen shot 2018-05-09 at 12 07 21 am

Here is my code:
screen shot 2018-05-09 at 12 08 57 am

screen shot 2018-05-09 at 12 09 16 am

My current react setup is simply the one I downloaded from here https://github.com/facebook/create-react-app.

Any ideas as to what is causing this issue? Really want to use this sticky table!

### LINKED ISSUE #49: jsfiddle or similar showcasing environment?
Hi,

Do you provide links to sources over a CDN? If not: please advise: is it possible to use showcasing environment like jsfiddle?

Best regards,
Vladimir

### LINKED ISSUE #67: upgrade react version
this is causing trouble in my react app

### LINKED ISSUE #68: add storybooks
using storybooks will make it easy to run examples locally, so we can make sure we don't break when changing something

### LINKED ISSUE #70: remove dist folder
we should use `prepare` npm script to build this package when publishing version to npm, instead of adding more noise on pull requests diffs

like this https://github.com/entria/mongo-aggregate-lodash/blob/master/package.json#L57

### LINKED ISSUE #71: upgrade to babel 7

### PR DESCRIPTION
**Pull request by sibelius**
…n tests

fix #67
fix #71
fix #70
fix #68 
fix #49
fix #38

How to run storybook (it was copied from gh-pages demo)

```jsx
yarn storybook
```

image

I went down the rabbit hole, where one upgrade leaves to another

escalated

### CODE REVIEW

**Comment by maxhudson** [comment]
Haha whoa!! Will check this out tonight

**Comment by sibelius** [comment]
friendly ping

**Comment by maxhudson** [comment]
@sibelius only two comments:

- can you remove package-lock.json and we'll commit to using yarn so as not to mix package managers?
- it looks like storybook packages are in `dependencies` when it seems like they should be in `devDependencies`

I would do both of these myself, but TBH I don't really know how to make modifications to someone else's forked PR

**Comment by sibelius** [comment]
image

I'm not sure either, I'm gonna update here

**Comment by sibelius** [comment]
everything is on devDependencies https://github.com/henrybuilt/react-sticky-table/pull/69/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R10

**Comment by sibelius** [comment]
updated without package-lock.json

**Comment by maxhudson** [comment]
Great - do you know how I can use storybook for the gh-pages branch? Otherwise ready to merge

**Comment by sibelius** [comment]
Check storybook docs

**Comment by maxhudson** [comment]
@sibelius thanks for the help!

**Comment by maxhudson** [comment]
@sibelius I missed it until now, but `dist` was added to .gitignore. react-sticky-table/index.js points to it, so not sure how that's working... Can you explain if you know?

**Comment by sibelius** [comment]
dist will be generated when publishing to npm from source

you need to make sure `main` field of `package.json` points out to correct compiled file

**Comment by maxhudson** [comment]
@sibelius cool - thanks. points to `dist/index.js` which seems right.

**Pull request merged**
