### PR TITLE
fixed scrollbar

### PR DESCRIPTION
**Pull request by cnaber1**
- Fixed regression in y-scrollbar
- offset in x-scrollbar when fixed row header

### CODE REVIEW

**Comment by maxhudson** [comment]
@cnaber1 I'll check this out today

**Comment by maxhudson** [comment]
The reason we don't do scrollbar like this, is the whitespace that appears [here](https://ibb.co/naL968)

Not sure what y-scrollbar regression you're referring to!

**Comment by cnaber1** [comment]
The y-scrollbar doesn't go all the way down when scrolling.

**Comment by dominikdosoudil** [comment]
I guess that it's the #46 and #47 problem

**Comment by maxhudson** [comment]
resolved in v3.0.1

**Pull request closed without merging**
